### ISSUE TITLE
Is Vue 2 supported yet?

### ISSUE THREAD

**Issue by bert1973** [madskristensen/AspNetCoreTemplatePack#3]
The VS 2015 version seems to supported Vue 2.
Will this be the case with the VS 2017 version also?

**Comment by madskristensen** [comment]
No, and it will not be in this template pack. Instead, take a look at this one http://vsixgallery.com/extension/4336beed-a389-4f86-9138-40d258e78ccf/

**Comment by bert1973** [comment]
Ok, thank you for pointing me in the right direction!
