### ISSUE TITLE
can't install on vs 2017

### ISSUE THREAD

**Issue by AlaaNassar** [madskristensen/AspNetCoreTemplatePack#5]
![06c95754a48e4af49178a82ece4bee90](https://cloud.githubusercontent.com/assets/24668676/26827999/f4571a38-4abf-11e7-8b59-aaf6b28bfe38.png)

**Comment by AlaaNassar** [comment]
it work only from the CLI

**Comment by ysma500** [comment]
What did you do to fix your issue?
I almost got the same problem: 
![image](https://user-images.githubusercontent.com/32311542/59719239-f37d6680-91e9-11e9-94a4-08e8d1f6a350.png)

**Comment by ysma500** [comment]
Found that I'm version VS2017.2 will try to update and see...
